#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Andou Aoki
# SPDX-LICENSE-Identifier: BSD-3-Clause

import sys


def tonum(s):   

    try:
        return int(s)
    except ValueError:
        return froat(s)


ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)

